name: Unit tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  run-unit-tests:
    name: Run unit tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'

      - name: Cache Maven dependencies
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Run unit tests
        run: mvn -B test

      - name: Publish test report
        uses: mikepenz/action-junit-report@v2
        if: always()
        with:
          check_name: Publish unit tests report
          require_tests: true
          report_paths: '**/target/*-reports/TEST-*.xml'

  run-integration-tests:
    name: Run integration tests
    runs-on: ubuntu-latest

    strategy:
      matrix:
        scylla-version: ['latest', '4.5.rc1', '4.4.1', '4.3.2']

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'

      - name: Cache Maven dependencies
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Run integration tests (Scylla version ${{ matrix.scylla-version }})
        run: mvn -B verify -Dtest=none -DfailIfNoTests=false -Dscylla.docker.version=${{ matrix.scylla-version }}

      - name: Publish test report (Scylla version ${{ matrix.scylla-version }})
        uses: mikepenz/action-junit-report@v2
        if: always()
        with:
          check_name: Publish integration tests report (Scylla version ${{ matrix.scylla-version }})
          require_tests: true
          report_paths: '**/target/*-reports/TEST-*.xml'
